
package hotel.management.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Checkin extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps;
    Statement st;
    /**
     * Creates new form Checkin
     */
    public Checkin() {
        initComponents();
        
        
        
       //______________this will show the current date in check in text field______________ 
        SimpleDateFormat obj =new SimpleDateFormat ("dd-MM-YYYY");
        Date date = new Date();
        txtCheckInDate.setText(obj.format(date));
       //__________________________________________________________________________________
        
        
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
             con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/desktophotel" , "root" , "");
        } catch (SQLException ex) {
            Logger.getLogger(Rooms.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        txtAddress = new javax.swing.JTextField();
        comboIdType = new javax.swing.JComboBox<>();
        txtIdNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCheckInDate = new javax.swing.JTextField();
        txtRoomNumber = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtRoomType = new javax.swing.JTextField();
        txtBedType = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        comboPayment = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtAdvance = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(80, 80, 1100, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkin.jpg"))); // NOI18N
        jLabel1.setText("Check in");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 204, 81));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 108, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 188, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 288, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 362, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 412, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Room Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 148, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 291, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Check in Date");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 108, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 105, 179, -1));
        getContentPane().add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 145, 179, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 185, 179, -1));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 227, -1, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 288, 179, 37));

        comboIdType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhaar Card", "Pan Card", "Voter Card", "Passport", "Driving Licence" }));
        getContentPane().add(comboIdType, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 359, -1, -1));
        getContentPane().add(txtIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 409, 179, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Room Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 196, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bed");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 236, -1, -1));

        txtCheckInDate.setEditable(false);
        txtCheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInDateActionPerformed(evt);
            }
        });
        getContentPane().add(txtCheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 105, 128, -1));

        txtRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 145, 128, -1));

        txtPrice.setEditable(false);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 288, 128, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Check in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 24, -1, -1));
        getContentPane().add(txtRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 196, 128, -1));
        getContentPane().add(txtBedType, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 236, 128, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 60, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 0));
        jLabel15.setText("Payment Mode");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        comboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Online" }));
        getContentPane().add(comboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Advance Payment\n(optional)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        txtAdvance.setText("0");
        getContentPane().add(txtAdvance, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 71, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkin BG (1).jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(txtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtName.requestFocus();
        }
        else if(txtMobile.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtMobile.requestFocus();
        }
        else if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtEmail.requestFocus();
        }
        else if(txtAddress.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtAddress.requestFocus();
        }
        else if(txtIdNumber.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtIdNumber.requestFocus();
        }
        else if(txtRoomNumber.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Every field must be filled");
            txtRoomNumber.requestFocus();
        }
        
        
        
        else{
            try {
                ps = con.prepareStatement("insert into customer  (name,mobile,email,address,gender,idType,idNumber,roomNumber,joindate,roomType,bed,price,status,paymentMode,advancePayment,checkOutDate,NumberofDays,discount,totalAmount) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
              
                ps.setString(1, txtName.getText());
                ps.setString(2, txtMobile.getText());
                ps.setString(3, txtEmail.getText());
                ps.setString(4, txtAddress.getText());
                ps.setString(5, comboGender.getItemAt(comboGender.getSelectedIndex()));
                ps.setString(6, comboIdType.getItemAt(comboIdType.getSelectedIndex()));
                ps.setString(7, txtIdNumber.getText());
                ps.setString(8, txtRoomNumber.getText());
                ps.setString(9, txtCheckInDate.getText());
                ps.setString(10, txtRoomType.getText());
                ps.setString(11, txtBedType.getText());
                ps.setString(12, txtPrice.getText());
                ps.setString(13, "Checked in");
                ps.setString(14, comboPayment.getItemAt(comboPayment.getSelectedIndex()));
                ps.setString(15, txtAdvance.getText());
                ps.setString(16, "");
                ps.setString(17, "0");
                ps.setString(18, "0");
                ps.setString(19, "0");
   
   
                 
                ps.executeUpdate();
                
                
            JOptionPane.showMessageDialog(this, "Successfully checked in");
            ps = con.prepareStatement("update room set status='Occupied' where roomNumber = ? "); 
            ps.setString(1, txtRoomNumber.getText());
            ps.executeUpdate();
            
             txtName.setText("");
             txtMobile.setText("");
             txtEmail.setText("");
             txtAddress.setText("");
             txtIdNumber.setText("");
             txtRoomNumber.setText("");
             txtRoomType.setText("");
             txtBedType.setText("");
             txtPrice.setText("");
             txtAdvance.setText("0");
        
           
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Checkin.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNumberActionPerformed
   
       
    }//GEN-LAST:event_txtRoomNumberActionPerformed

    private void txtCheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInDateActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            ps = con.prepareStatement("Select status from room where roomNumber=?");
            ps.setString(1,txtRoomNumber.getText());
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String status =  rs.getString("status");
                if(status.equals("Occupied")){
                    txtRoomType.setText("");
                    txtBedType.setText("");
                    txtPrice.setText("");
                    JOptionPane.showMessageDialog(this, "Room already Booked");
                    
                }
                
                else{
                        ps = con.prepareStatement("Select status,roomType,bed,price from room where roomNumber=?");
            ps.setString(1,txtRoomNumber.getText());
             rs = ps.executeQuery();
           
           
            
            while(rs.next()){
              String roomType =  rs.getString("roomType");
              String Bed = rs.getString("bed");
              String Price = rs.getString("price");
                                
              txtRoomType.setText(roomType);
              txtBedType.setText(Bed);
              txtPrice.setText(Price);
                
            }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Checkin.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

             txtName.setText("");
             txtMobile.setText("");
             txtEmail.setText("");
             txtAddress.setText("");
             txtIdNumber.setText("");
             txtRoomNumber.setText("");
             txtRoomType.setText("");
             txtBedType.setText("");
             txtPrice.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboIdType;
    private javax.swing.JComboBox<String> comboPayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdvance;
    private javax.swing.JTextField txtBedType;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdNumber;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtRoomType;
    // End of variables declaration//GEN-END:variables
}
